# Generated by Django 5.1 on 2024-09-13 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
